import{bears,questions}from'./data.js';import{getBear,scoreAnswers,shareUrl,traitValues}from'./scoring.js';
const $=s=>document.querySelector(s),app=$('#app');let answers=[],step=-1,resultData=null,direct=false;
function el(tag,attrs={},...children){const node=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')node.className=v;else if(k.startsWith('on'))node.addEventListener(k.slice(2).toLowerCase(),v);else node.setAttribute(k,v)}for(const child of children)node.append(child?.nodeType?child:document.createTextNode(String(child??'')));return node}
function shell(content){app.replaceChildren(content);content.querySelector('button,a')?.focus({preventScroll:true})}
function start(){direct=false;answers=[];step=-1;history.replaceState(null,'',location.pathname);shell(el('section',{class:'start panel'},el('p',{class:'kicker'},'FIELD TEST / SPW–11'),el('h1',{},'WHICH FAT BEAR ARE YOU?'),el('p',{class:'lede'},'Seven questions. Zero scientific validity. One enormous truth.'),el('button',{class:'primary',onClick:()=>{step=0;renderQuestion()}},'FIND MY BEAR'),el('p',{class:'fine'},'Scientifically meaningless. Spiritually significant.')))}
function renderQuestion(){const q=questions[step],fieldset=el('fieldset',{}),legend=el('legend',{},q.text);fieldset.append(legend);q.answers.forEach((a,i)=>{const button=el('button',{class:'answer'+(answers[step]===i?' selected':''),type:'button',onClick:()=>{answers[step]=i;if(step<questions.length-1){step++;renderQuestion()}else showResult(scoreAnswers(answers),false)}},el('span',{class:'letter'},String.fromCharCode(65+i)),el('span',{},a.text));fieldset.append(button)});const back=el('button',{class:'back',type:'button',onClick:()=>{if(step===0)start();else{step--;renderQuestion()}}},'← BACK');shell(el('section',{class:'quiz panel'},el('div',{class:'progress'},el('span',{},`FIELD QUESTION ${step+1} / ${questions.length}`),el('progress',{max:questions.length,value:step+1,'aria-label':`Question ${step+1} of ${questions.length}`})),fieldset,back))}
function bearArt(bear){return el('div',{class:'bear-art','aria-hidden':'true',style:`--accent:${bear.accent}`},el('span',{class:'bear-shape'},'●'))}
function showResult(scored,isDirect){const bear=scored.bear;resultData=scored;direct=isDirect;const traitData=isDirect?bear.traits.map((label,i)=>({label,value:[88,76,67][i]})):traitValues(scored.totals,bear);const card=el('section',{class:'result-card',style:`--accent:${bear.accent}`},el('div',{class:'card-top'},el('span',{},'WHICH FAT BEAR ARE YOU?'),el('span',{},`SPECIMEN ${bear.bearNumber}`)),el('p',{class:'reveal-label'},isDirect?'SOMEONE GOT':'YOUR BEAR IS'),el('h1',{},bear.displayName),el('h2',{},bear.archetype),bearArt(bear),el('p',{class:'playful'},bear.playfulSummary),el('div',{class:'trait-row'},...traitData.map(t=>el('div',{class:'trait'},el('span',{},t.label),el('strong',{},`${t.value}%`),el('div',{class:'meter','aria-label':`${t.label}: ${t.value} percent`},el('i',{style:`width:${t.value}%`}))))));const share=el('button',{class:'primary',onClick:shareResult},isDirect?'SHARE THIS BEAR':'SHARE MY BEAR');const facts=el('section',{class:'facts'},el('p',{class:'kicker'},'MEET THE REAL BEAR'),el('h3',{},bear.factualSummary),el('ul',{},...bear.facts.map(f=>el('li',{},f))),el('p',{class:'fact-note'},'Bear identities and annual rosters change. Bear facts draw on National Park Service information; the personality reading above is comedy.'),el('a',{href:bear.sources[0],target:'_blank',rel:'noopener noreferrer'},'Read more from the NPS ↗'));const actions=el('div',{class:'actions'},share,el('button',{class:'secondary',onClick:start},isDirect?'TAKE THE QUIZ':'RETAKE QUIZ'),el('p',{id:'share-status',class:'share-status','aria-live':'polite'},''));shell(el('div',{class:'result'},card,actions,facts))}
async function shareResult(){const bear=resultData.bear,url=shareUrl(bear),text=direct?`Meet ${bear.displayName}: ${bear.archetype}. Which Fat Bear are you?`:`Apparently I’m ${bear.displayName}: ${bear.archetype}. Find your Fat Bear:`;try{if(navigator.share)await navigator.share({title:'Which Fat Bear Are You?',text,url});else{await navigator.clipboard.writeText(`${text} ${url}`);$('#share-status').textContent='RESULT LINK COPIED.'}}catch(error){if(error.name!=='AbortError')$('#share-status').textContent='COPY FAILED — COPY THE ADDRESS BAR.'}}
document.head.append(el('link',{rel:'stylesheet',href:'/mobile-fixes.css'}));const raw=new URLSearchParams(location.search).get('bear');const bear=raw&&/^[a-z0-9-]+$/.test(raw)?getBear(raw):null;if(bear)showResult({bear,totals:null},true);else start();
