export const dimensions=['social','bold','patient','chaotic','comfort','competitive','food','independent'];

const NPS2022='https://www.nps.gov/katm/learn/fat-bear-week-2022.htm';
const NPSHISTORY='https://www.nps.gov/katm/learn/nature/fat-bear-week-past-and-present.htm';

export const bears=[
 {id:'747',bearNumber:'747',displayName:'Bear 747',archetype:'THE ABSOLUTE UNIT',factualSummary:'747 is a very large adult male and a highly skilled fisher documented at Brooks River. He won Fat Bear Week in 2020 and 2022.',facts:['One of the largest bears known to use Brooks River.','Recognizable by his blocky muzzle and heavily scarred coat.','Fat Bear Week champion in 2020 and 2022.'],playfulSummary:'You treat abundance as a reasonable baseline. Problems tend to reconsider once you arrive.',traits:['SNACK AUTHORITY','UNBOTHERED','PRESENCE'],profile:[1,5,2,0,4,5,5,3],accent:'#d85d2a',sources:[NPSHISTORY,NPS2022]},
 {id:'480-otis',bearNumber:'480',displayName:'480 Otis',archetype:'THE PATIENT VETERAN',factualSummary:'480 Otis is an older Brooks River male known for patient fishing strategies. He has won Fat Bear Week four times.',facts:['First identified at Brooks River in 2001.','Often uses a sit-and-wait fishing approach.','Champion in 2014, 2016, 2017 and 2021.'],playfulSummary:'You know that urgency is frequently just impatience wearing a lanyard.',traits:['PATIENCE','QUIET CONFIDENCE','SNACK TIMING'],profile:[1,1,5,0,4,1,4,5],accent:'#8b6f47',sources:[NPS2022,NPSHISTORY]},
 {id:'128-grazer',bearNumber:'128',displayName:'128 Grazer',archetype:'THE FORCE OF NATURE',factualSummary:'128 Grazer is an adult female frequently seen at Brooks River and a two-time Fat Bear Week champion.',facts:['Known by her blond ears and long, straight muzzle.','An accomplished fisher at Brooks Falls.','Fat Bear Week champion in 2023 and 2024.'],playfulSummary:'You are warm, capable, and absolutely not available for nonsense.',traits:['BOUNDARIES','FOCUS','MAIN CHARACTER'],profile:[2,5,2,1,1,5,3,4],accent:'#b8462f',sources:[NPSHISTORY,NPS2022]},
 {id:'32-chunk',bearNumber:'32',displayName:'32 Chunk',archetype:'THE COMEBACK',factualSummary:'32 Chunk is a large adult male documented at Brooks River. He became Fat Bear Week champion in 2025.',facts:['A large adult male with a prominent brow ridge.','Frequently fishes at Brooks Falls.','Fat Bear Week champion in 2025.'],playfulSummary:'Your strategy is persistence, followed by more persistence, followed by a very satisfying lunch.',traits:['DRIVE','RESILIENCE','BIG FINISH'],profile:[2,4,3,2,1,5,4,3],accent:'#704f3b',sources:[NPSHISTORY,NPS2022]},
 {id:'151-walker',bearNumber:'151',displayName:'151 Walker',archetype:'THE ADAPTABLE ONE',factualSummary:'151 Walker is a large adult male and a frequent Brooks Falls user with a broad range of fishing spots.',facts:['First identified as an independent young bear in 2009.','Has fished from several locations at Brooks Falls.','Documented as a skilled lip fisher.'],playfulSummary:'You have a plan, a backup plan, and the confidence to pretend the backup was always the plan.',traits:['ADAPTABILITY','COMPETENCE','RANGE'],profile:[3,3,3,2,1,3,3,4],accent:'#396b61',sources:[NPS2022]},
 {id:'164',bearNumber:'164',displayName:'Bear 164',archetype:'THE CHAOS INTERN',factualSummary:'164 is a younger adult male documented at Brooks River, identifiable by blond oval ears and a dark indentation on his upper muzzle.',facts:['First identified as a subadult in 2019.','His coat darkens between spring and fall.','Recognized by blond, oval-shaped ears.'],playfulSummary:'You bring initiative, momentum, and one completely avoidable complication.',traits:['CHAOS','CURIOSITY','MOMENTUM'],profile:[4,3,1,5,0,2,3,1],accent:'#dc7d22',sources:[NPS2022]},
 {id:'901',bearNumber:'901',displayName:'Bear 901',archetype:'THE SOCIAL CLIMBER',factualSummary:'901 is an adult female documented at Brooks River. She was first identified as a young independent bear in 2018.',facts:['Recognizable by blond-rimmed triangular ears.','Has a darker face and lighter muzzle.','First identified at Brooks River in 2018.'],playfulSummary:'You enter with excellent timing and somehow leave with the best story.',traits:['SOCIAL ENERGY','BOLDNESS','GOOD TIMING'],profile:[5,4,1,4,1,3,3,0],accent:'#c45372',sources:[NPS2022]},
 {id:'856',bearNumber:'856',displayName:'Bear 856',archetype:'THE BOARD CHAIR',factualSummary:'856 is a large adult male and long-documented dominant bear at Brooks Falls.',facts:['First observed at Brooks River as a young adult in 2006.','Recognizable by a lighter brown coat and light-tipped ears.','Documented as one of the most dominant bears at Brooks Falls.'],playfulSummary:'You do not raise your voice. The room simply updates its priorities.',traits:['AUTHORITY','PERSONAL SPACE','DECISIVENESS'],profile:[0,5,2,1,1,5,2,5],accent:'#263f3a',sources:[NPS2022]}
];

const A=(text,scores)=>({text,scores});
export const questions=[
 {text:'Someone reaches for your fries.',answers:[A('We can share. I have evolved.',[5,0,3,0,2,0,1,0]),A('Their hand has made a strategic error.',[0,5,0,1,0,5,2,4]),A('I already ate theirs.',[3,3,0,5,0,2,5,0]),A('I ordered enough to survive this exact event.',[1,1,4,0,5,1,5,3])]},
 {text:'Your ideal Saturday has one objective.',answers:[A('See everyone. Briefly.',[5,2,1,2,1,1,1,0]),A('Become horizontal.',[0,0,4,0,5,0,2,4]),A('Win something nobody knew was competitive.',[2,4,1,3,0,5,2,2]),A('Follow a snack-based itinerary.',[2,1,2,1,4,1,5,2])]},
 {text:'The plan changes at the last minute.',answers:[A('Excellent. A plot twist.',[4,3,0,5,0,2,1,0]),A('I calmly produce Plan B.',[2,3,4,0,1,3,1,4]),A('I require 20–30 business minutes.',[0,0,5,0,5,0,1,4]),A('The plan was always merely a suggestion.',[3,4,1,4,1,2,1,2])]},
 {text:'Pick a personal motto.',answers:[A('Good things come to those who sit near snacks.',[0,0,5,0,4,0,5,4]),A('Be difficult to move.',[0,5,3,0,3,5,3,5]),A('This could be funnier.',[4,2,0,5,1,1,2,0]),A('Observe. Adapt. Secure lunch.',[1,3,5,1,2,3,5,4])]},
 {text:'A group chat has 47 unread messages.',answers:[A('I caused at least 30.',[5,3,0,5,0,2,1,0]),A('I react with one perfect emoji.',[3,1,4,1,3,0,1,3]),A('Muted since 2019.',[0,0,5,0,5,0,2,5]),A('I read everything and issue a summary.',[2,3,4,0,1,4,1,3])]},
 {text:'You arrive at a buffet.',answers:[A('One plate. Architectural.',[1,4,2,1,2,4,5,3]),A('I survey the terrain first.',[0,2,5,0,1,3,4,5]),A('I make friends in the dessert queue.',[5,2,1,3,3,1,5,0]),A('I have trained for this.',[2,5,2,2,2,5,5,2])]},
 {text:'Your conflict style?',answers:[A('Direct, concise, over by lunch.',[1,5,2,0,1,5,2,4]),A('Wait. Watch. Pick the moment.',[0,2,5,0,2,3,1,5]),A('Deploy charm and a suspicious anecdote.',[5,2,1,4,1,1,1,0]),A('Leave. I have a blanket elsewhere.',[0,0,4,0,5,0,1,5])]}
];
